config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#home", as: :root
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :ideas

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :update, :edit]

  resource :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      can :manage, :all
    end

    alias_action :create, :read, :update, :destroy, to: :crud

    can :crud, Idea, user_id: user.id

    can :crud, Review do |review|
      puts review.user.id
      puts user.id
      review.user.id == user.id || review.idea.user.id == user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many(:reviews, dependent: :destroy)
end

app/models/review.rb
class Review < ApplicationRecord

  # create the association of the foreign key
  belongs_to :idea
  belongs_to :user

  #make the presence of body text mandatory
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas
  has_many :reviews

  has_secure_password

  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :first_name, presence: true

  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  helper_method(:current_user)

  def user_signed_in?
    current_user.present?
  end

  helper_method(:user_signed_in?)

  def authenticate_user!
    unless user_signed_in?
      flash[:danger] = "You must sign in or sign up first"
      redirect_to new_sessions_path
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :welcome]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:destroy, :edit, :update]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new params.require(:idea).permit(:title, :body)
    @idea.user = current_user
    if @idea.save
      flash[:success] = "idea created successfully"
      redirect_to idea_path(@idea.id)
    else
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:success] = "Idea deleted successfully"
    redirect_to ideas_path
  end

  def index
    @ideas = Idea.all.order(created_at: :desc)
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update params.require(:idea).permit(:title, :body)
      flash[:success] = "idea updated successfully"
      redirect_to idea_path(@idea.id)
    else
      flash[:danger] = "idea not updated"
      render :edit
    end
  end

  private

  def authorize_user!
    redirect_to root_path, alert: "access denied" unless can? :crud, @idea
  end

  def find_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :welcome]
  before_action :find_review, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:destroy, :edit, :update]

  def create
    @idea = Idea.find params[:idea_id]
    @review = Review.new review_params
    @review.idea = @idea
    @review.user = current_user
    if @review.save
      redirect_to idea_url(@idea.id)
    else
      @reviews = @idea.reviews.order(created_at: :desc)
      render "ideas/show"
    end
  end

  def destroy
    @review = Review.find params[:id]
    @review.destroy
    redirect_to idea_url(@review.idea)
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end

  def authorize_user!
    redirect_to root_path, alert: "access denied" unless can? :crud, @review
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Logged In"
      redirect_to ideas_path
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to ideas_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password, :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @root = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/edit.html.erb
<div class="formCenter">


<%= form_with(model: @idea, local: true ) do |form| %>


  <% if @idea.errors.present? %>
    <p class="form-errors">
      <%= @idea.errors.full_messages.join(", ") %>
    </p>
  <% end %>


   <div class="form-group">
    <%= form.label :title %> <br />
    <%= form.text_field :title , class: "form-control"%>
  </div>
   <div class="form-group">
  <%= form.label :Content %> <br />
      <%= form.text_area(
        :body,
        cols: 50,
        rows: 5,
        class: "form-control"
      ) %>
  </div>
  <%= form.submit "Update" , class: "btn btn-lg btn-outline-dark"%>

  <% end %>

</div>

app/views/ideas/index.html.erb
<div class="ideaShow">

<% @ideas.each do |idea| %>
    <div class="idea-card">
      <div class="idea-title">
        <i class="far fa-plus-square"></i>
        <%= link_to idea.title, idea_path(idea.id)  %> 
      </div>
      <div class="idea-body" style="display: none">

        <%= idea.body %>
        <br>
        <small>
          Submitted by <%= idea.user&.full_name || 'DELETED' %>
          Created <%= time_ago_in_words(idea.created_at) %> ago
        </small>
      </div>
    </div>
     <hr>
<% end %>
</div>

app/views/ideas/new.html.erb
 <div class="formCenter">
 <%= form_with(model: @idea, local: true ) do |form| %>
  <div class="form-group">
  <% if @idea.errors.present? %>
    <p class="form-errors">
      <%= @idea.errors.full_messages.join(", ") %>
    </p>
  <% end %>

  <div class="form-group">
    <%= form.label :idea,  style: "font-size: 20px"  %> <br />
    <%= form.text_field :title, style: "width: 100%", class: "form-control" %>
  </div>
  <div class="form-group">
  <%= form.label :Description, style: "font-size: 20px" %>
      <%= form.text_area(
        :body,
        cols: 50,
        rows: 3,
        class: "form-control"
      ) %>
  </div>

  <%= form.submit "Create Idea", class: "btn btn-lg btn-outline-dark" %>
</div>
  <% end %>
</div>

app/views/ideas/show.html.erb
<div class="ideaShow">

<div class="idea-title"><%= @idea.title %></div>

<div class="idea-body"><%= @idea.body %>
<br>

  <small>
    Posted by <%= @idea.user&.full_name || 'DELETED' %>
    <%= time_ago_in_words(@idea.created_at) %> ago
  </small>

</div>

<div class="idea-edit-delete">
  <% if can?(:update, @idea) %>
      <%= link_to "Edit", 
      edit_idea_path(@idea.id), 
     class: "btn btn-lg btn-outline-dark" %>
  <% end  %>
  
  <% if can?(:destroy, @idea) %>

      <%= link_to "Delete", 
        idea_path(@idea.id), 
        method: :delete, data: { confirm: "Are you sure?" }, 
        class: "btn btn-lg btn-outline-dark" %>
  <% end %>
</div>

<%= form_with(model: [@idea, @review], local: true) do |f| %>
   <% if @review.errors.present? %>
     <p class="form-errors">
       <%= @review.errors.full_messages.join(", ") %>
     </p>
   <% end %>

   <div class="form-group">
     <%= f.text_area(
       :body,
       cols: 50,
       rows: 2,
       placeholder: "What are your thoughts?",
       class: "form-control"
     ) %>
   </div>
   <%= f.submit "Submit Comment", class: "btn btn-lg btn-outline-dark" %>
 <% end %>
<br>

 <ul class="comment-list">
   <% @reviews.each do |review| %>
     <li>
       <p>
         <%= review.body %> <br>
          <small>
           Commented by <%= review.user&.full_name || 'DELETED' %>
            <%= time_ago_in_words(review.created_at) %> ago
          <% if can?(:update, review) %>
             <%=
               link_to(
                 "Delete",
                 idea_review_path(@idea, review),
                 method: :delete,
                 data: {
                   confirm: "Are you sure?"
                 }
               )
             %>
          <% end %>
         </small>
       </p>
     </li>
   <% end %>
 </ul>

 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Startup Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
</head>
<body>
  <header>

      <div class="top-nav" style="display: flex; justify-content: space-between;align-items:center">
        <div >
        
            <a class="nav-item nav-link form-inline"" href="/">
              <div class="brand">
                <i class="far fa-lightbulb"></i> STARTUP IDEA FACTORY
              </div>
            </a>
          
        </div>
        <div >
          <ul class="navbar-nav ml-auto">
            <%= link_to 'New Idea  |', new_idea_path, class: "nav-item nav-link form-inline" %>
            <%= link_to 'All Ideas |', ideas_path, class: "nav-item nav-link form-inline" %>
            <% if user_signed_in? %>
              <span class="nav-item  form-inline"> Hello&nbsp<%= current_user.full_name %> |</span>
              <%= link_to "Sign Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to sign out?"}, class: "nav-item nav-link form-inline" %>
            <% else %>
              <%= link_to "Sign In |", new_sessions_path, class: "nav-item nav-link form-inline" %>
              <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link form-inline" %>
            <% end %>
          </ul>
        </div>
      </div>

  </header>
  <% if @root %>
    <div class="header2">
    <% else%>
      <div class="container" >
      <% end %>
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</main>
</body>
</html>

app/views/users/new.html.erb
<div class="formCenter">
<%= form_with model: @user, local: true do |f| %>

 <% if @user.errors.any? %>
   <p>
     <%= @user.errors.full_messages.join(", ")  %>
   </p>
 <% end %>

 <div class="form-group">
   <%= f.label :first_name %>
   <%= f.text_field :first_name, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :last_name %>
   <%= f.text_field :last_name, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :email %>
   <%= f.email_field :email, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :password %>
   <%= f.password_field :password, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation, class: "form-control" %>
 </div>
 <br>

 <%= f.submit "Sign Up" , class: "btn btn-lg btn-outline-dark" %>
<% end %>
 
 </div>

app/views/welcome/home.html.erb
  <header2>
  
  <section class="header-content">
    <h1 class="header-title animate-pop-in">Welcome to Startup Idea Factory</h1>
    <h5 class="header-subtitle animate-pop-in">Crowdsourcing innovative ideas</h5>
    <p class="sign-up header-button animate-pop-in"><a href="/users/new" class="button">Click here to sign up</a></p>
  </section>
</header2>